package docsgen

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const subReadme = `# sub

Package sub is a nested fixture package used to assert docsgen documents
subpackages, not just the module root.

## Reference

- API: <https://pkg.go.dev/example.com/sample/sub>
- Guide: [sub guide](https://example.com/sample/wiki/Sub)

<!-- Generated by cmd/docsgen (MC-11). Do not edit; run ` + "`make docs`" + `. -->
`

// copyFixture copies testdata/sample into a fresh temp dir so tests never
// write generated README.md files back into the repo's testdata tree.
func copyFixture(t *testing.T) string {
	t.Helper()

	dst := t.TempDir()
	src := filepath.Join("testdata", "sample")

	err := filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)

		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o644)
	})
	require.NoError(t, err)

	return dst
}

func TestGenerate_RendersDocumentedPackages(t *testing.T) {
	root := copyFixture(t)

	err := Generate(root, Config{WikiBaseURL: "https://example.com/sample/wiki"})
	require.NoError(t, err)

	got, err := os.ReadFile(filepath.Join(root, "sub", "README.md"))
	require.NoError(t, err)
	assert.Equal(t, subReadme, string(got))
}

func TestGenerate_SkipsExcludedAndUndocumentedPackages(t *testing.T) {
	root := copyFixture(t)

	err := Generate(root, Config{WikiBaseURL: "https://example.com/sample/wiki"})
	require.NoError(t, err)

	skipped := []string{
		".", // module root: hand-authored README.md, never generated
		filepath.Join("cmd", "tool"),
		filepath.Join("internal", "helper"),
		filepath.Join("examples", "demo"),
		"nodoc",
		"empty",
	}
	for _, dir := range skipped {
		_, err := os.Stat(filepath.Join(root, dir, "README.md"))
		assert.Truef(t, os.IsNotExist(err), "expected no README.md under %s", dir)
	}
}

func TestGenerate_LogsDocumentedAndSkippedPackages(t *testing.T) {
	root := copyFixture(t)

	var lines []string
	err := Generate(root, Config{Logf: func(format string, args ...any) {
		lines = append(lines, fmt.Sprintf(format, args...))
	}})
	require.NoError(t, err)

	var wrote, skip int
	for _, l := range lines {
		switch {
		case strings.Contains(l, "docsgen: wrote"):
			wrote++
		case strings.Contains(l, "docsgen: skip"):
			skip++
		}
	}
	assert.Equal(t, 1, wrote) // sample/sub (module root is denylisted, never a wrote/skip line)
	assert.Equal(t, 2, skip)  // nodoc, empty
}

func TestGenerate_DefaultsWikiBaseFromModulePath(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(root, "go.mod"), []byte("module github.com/example/ghsample\n\ngo 1.26\n"), 0o644))
	require.NoError(t, os.MkdirAll(filepath.Join(root, "widget"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, "widget", "widget.go"), []byte("// Package widget is a fixture for the default wiki base test.\npackage widget\n\n// Value is exported so widget has an exported identifier.\nconst Value = 1\n"), 0o644))

	require.NoError(t, Generate(root, Config{}))

	got, err := os.ReadFile(filepath.Join(root, "widget", "README.md"))
	require.NoError(t, err)
	assert.Contains(t, string(got), "https://github.com/example/ghsample/wiki/Widget")
}

func TestGenerate_OmitsGuideLineWhenWikiBaseEmpty(t *testing.T) {
	root := copyFixture(t) // example.com/sample: non-github.com, so defaultWikiBase("") stays ""

	require.NoError(t, Generate(root, Config{}))

	got, err := os.ReadFile(filepath.Join(root, "sub", "README.md"))
	require.NoError(t, err)
	content := string(got)

	assert.Contains(t, content, "- API: <https://pkg.go.dev/example.com/sample/sub>")
	assert.NotContains(t, content, "- Guide:")
	assert.NotContains(t, content, "/Sub)") // no malformed empty-base link
}

func TestGenerate_IsDeterministic(t *testing.T) {
	root := copyFixture(t)

	require.NoError(t, Generate(root, Config{WikiBaseURL: "https://example.com/sample/wiki"}))
	first, err := os.ReadFile(filepath.Join(root, "sub", "README.md"))
	require.NoError(t, err)

	require.NoError(t, Generate(root, Config{WikiBaseURL: "https://example.com/sample/wiki"}))
	second, err := os.ReadFile(filepath.Join(root, "sub", "README.md"))
	require.NoError(t, err)

	assert.Equal(t, first, second)
}

func TestGenerate_MissingGoMod(t *testing.T) {
	root := t.TempDir()

	err := Generate(root, Config{})
	assert.Error(t, err)
}

func TestDiscoverDirs_ExcludesRootAndSkipDirs(t *testing.T) {
	root := copyFixture(t)

	dirs, err := discoverDirs(root)
	require.NoError(t, err)

	sort.Strings(dirs)
	for _, d := range dirs {
		assert.NotEqual(t, root, d)
	}

	var rels []string
	for _, d := range dirs {
		rel, err := filepath.Rel(root, d)
		require.NoError(t, err)
		rels = append(rels, filepath.ToSlash(rel))
	}
	assert.Contains(t, rels, "sub")
	assert.Contains(t, rels, "nodoc")
	assert.Contains(t, rels, "empty")
	assert.NotContains(t, rels, "cmd/tool")
	assert.NotContains(t, rels, "internal/helper")
	assert.NotContains(t, rels, "examples/demo")
}

func TestDefaultWikiBase(t *testing.T) {
	assert.Equal(t, "https://github.com/dangernoodle-io/shesha/wiki", defaultWikiBase("github.com/dangernoodle-io/shesha"))
	assert.Equal(t, "", defaultWikiBase("example.com/sample"))
}

func TestPageName(t *testing.T) {
	assert.Equal(t, "Sample", pageName("example.com/sample", "example.com/sample"))
	assert.Equal(t, "Sub", pageName("example.com/sample/sub", "example.com/sample"))
	assert.Equal(t, "Host-Generic", pageName("github.com/dangernoodle-io/shesha/host/generic", "github.com/dangernoodle-io/shesha"))
}

func TestReadModulePath_NoModuleDirective(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(root, "go.mod"), []byte("go 1.26\n"), 0o644))

	_, err := readModulePath(root)
	assert.Error(t, err)
}

func TestLoadPackageDoc_CountsTypeMethodsAndFuncs(t *testing.T) {
	root := t.TempDir()
	src := `// Package widget is a fixture exercising type-associated funcs/methods.
package widget

// Widget is exported only via its constructor and method below.
type Widget struct{}

// NewWidget constructs a Widget; go/doc associates it with Widget rather
// than the package's top-level Funcs.
func NewWidget() *Widget { return &Widget{} }

// Spin is a method on Widget.
func (w *Widget) Spin() {}
`
	require.NoError(t, os.WriteFile(filepath.Join(root, "widget.go"), []byte(src), 0o644))

	pkg, ok, err := loadPackageDoc(root, "example.com/widget")
	require.NoError(t, err)
	assert.True(t, ok)
	assert.Equal(t, 1, len(pkg.Types))
	assert.Equal(t, 3, exportedCount(pkg)) // Widget (type) + NewWidget (t.Funcs) + Spin (t.Methods)
}

func TestToImportPath_RelErrorFallsBackToModulePath(t *testing.T) {
	// filepath.Rel returns an error when it can't relate an absolute base
	// to a relative target (or vice versa); toImportPath falls back to
	// modulePath in that case.
	got := toImportPath("example.com/sample", "/abs/root", "relative/dir")
	assert.Equal(t, "example.com/sample", got)
}

func TestRun_DefaultFlags(t *testing.T) {
	root := copyFixture(t)
	t.Chdir(root)

	var stdout, stderr bytes.Buffer
	err := Run(nil, &stdout, &stderr)
	require.NoError(t, err)

	_, err = os.Stat(filepath.Join(root, "sub", "README.md"))
	assert.NoError(t, err)
}

func TestRun_RootWikiVerboseFlags(t *testing.T) {
	root := copyFixture(t)

	var stdout, stderr bytes.Buffer
	err := Run([]string{"-root", root, "-wiki", "https://example.com/sample/wiki", "-v"}, &stdout, &stderr)
	require.NoError(t, err)

	assert.Contains(t, stdout.String(), "docsgen: wrote")
	assert.Empty(t, stderr.String())

	got, err := os.ReadFile(filepath.Join(root, "sub", "README.md"))
	require.NoError(t, err)
	assert.Equal(t, subReadme, string(got))
}

func TestRun_ErrorBadRoot(t *testing.T) {
	var stdout, stderr bytes.Buffer
	err := Run([]string{"-root", filepath.Join(t.TempDir(), "does-not-exist")}, &stdout, &stderr)
	assert.Error(t, err)
}

func TestRun_ErrorBadFlag(t *testing.T) {
	var stdout, stderr bytes.Buffer
	err := Run([]string{"-not-a-real-flag"}, &stdout, &stderr)
	assert.Error(t, err)
	assert.NotEmpty(t, stderr.String())
}

func TestGenerate_WriteFileError(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("directory write-permission semantics differ on windows")
	}
	if os.Geteuid() == 0 {
		t.Skip("root ignores directory write permissions")
	}

	root := copyFixture(t)
	subDir := filepath.Join(root, "sub")
	require.NoError(t, os.Chmod(subDir, 0o500))
	t.Cleanup(func() { _ = os.Chmod(subDir, 0o755) })

	err := Generate(root, Config{WikiBaseURL: "https://example.com/sample/wiki"})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "write")
}

func TestLoadPackageDoc_ReadDirError(t *testing.T) {
	_, ok, err := loadPackageDoc(filepath.Join(t.TempDir(), "does-not-exist"), "example.com/x")
	assert.False(t, ok)
	assert.Error(t, err)
}

func TestLoadPackageDoc_ParseError(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "broken.go"), []byte("package broken(\n"), 0o644))

	_, ok, err := loadPackageDoc(dir, "example.com/broken")
	assert.False(t, ok)
	assert.Error(t, err)
}

func TestLoadPackageDoc_NoNonTestGoFiles(t *testing.T) {
	dir := t.TempDir()
	// Only a _test.go file present: it's excluded, leaving zero files and
	// thus zero distinct package names.
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pkg_test.go"), []byte("package onlytest\n"), 0o644))

	pkg, ok, err := loadPackageDoc(dir, "example.com/onlytest")
	require.NoError(t, err)
	assert.False(t, ok)
	assert.Nil(t, pkg)
}

func TestDiscoverDirs_UnreadableSubdirError(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("directory permission semantics differ on windows")
	}
	if os.Geteuid() == 0 {
		t.Skip("root ignores directory read permissions")
	}

	root := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.com/unreadable\n\ngo 1.26\n"), 0o644))
	blocked := filepath.Join(root, "blocked")
	require.NoError(t, os.MkdirAll(blocked, 0o755))
	require.NoError(t, os.Chmod(blocked, 0o000))
	t.Cleanup(func() { _ = os.Chmod(blocked, 0o755) })

	_, err := discoverDirs(root)
	assert.Error(t, err)

	err = Generate(root, Config{})
	assert.Error(t, err)
}
